apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    mathchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        images: huhaiwen/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: ifNotPresent
        env: 
        - name: branch
          value: <BRANCH>