apiVersion: apps/v1
kind: Deployments
metadata:
  name: jenkins-demo
spec:
  selector:
    mathchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        images: huhaiwen/k8s
	imagePullPolicy: ifNotPresent
	env: 
	- name: branch
	  value: master